### ISSUE TITLE
Some problem with uploading image

### ISSUE THREAD

**Issue by oniyakun** [brussell98/catgirls-api#12]
Hello! I'm studying ur project and try to build the site, but somehow when I uploading the image it always shows loading and API returns empty, you have any ideas about this? Huge thanks!

**Comment by oniyakun** [comment]
I figured out the problem is
![image](https://user-images.githubusercontent.com/30280837/69826750-81588580-124f-11ea-8f4d-d1b8432eebc9.png)
and modified the code to made it work, but new problem is, the uploaded image cannot load and returned 404`(/image/XXXXX & /thumbnail/XXXXX)`, Im still trying to fix it so if u know something plz let me know, thx!

**Comment by brussell98** [comment]
Read the error: "No such file or directory". You need to create them.

**Comment by oniyakun** [comment]
Somehow the system cannot recognition the path about `/../../../`, I delete them at ImagesPOST.js in line 110 &119 and it looks work fine. But now it can't load the image at the site I still dont know why

**Comment by oniyakun** [comment]
I dont seen any router about /image/ so I'm thinking maybe something wrong with my configuration or something

**Comment by oniyakun** [comment]
Holy... The `image` and `thumbnail` folder was outside of the `api` folder, I didnt realize that before... All in all, Thanks!
