### ISSUE TITLE
danbooru

### ISSUE THREAD

**Issue by Kadantte** [brussell98/catgirls-api#17]
Hi, Does Danbooru needs a Key or what? cause if I tried to download from it the website return this message! btw I'm using an Admin Account on Neko website.

![image](https://user-images.githubusercontent.com/11579313/123120353-28a59a80-d43c-11eb-8596-f925885d8d53.png)

```json
// http://localhost:8000/api/v1/proxy/danbooru?url=https:%2F%2Fcdn.donmai.us%2Foriginal%2F61%2Ffa%2F61fa635cfed870e8de8a9305026f486a.jpg

{
  "message": "Authentication required"
}
```
btw API grab everything except for the image!

![image](https://user-images.githubusercontent.com/11579313/123120480-3fe48800-d43c-11eb-8b2a-c9e332b539fa.png)

**Comment by brussell98** [comment]
You are not sending the token to the API from the website. Uploading, and thus image proxy, require valid authorization.

**Comment by Kadantte** [comment]
Shouldn't the website send the token by Auto? I mean if I'm already login it should be automated!

**Comment by brussell98** [comment]
It does, as can be seen on Nekos.moe. You have to have changed it

**Comment by Kadantte** [comment]
I didn't change anything, I just checked on neko.moe and it works just fine I dunno what's going on here tbh!

**Comment by Kadantte** [comment]
I re-downloaded the whole project ai and website and still the same problem!
I think this is good enough to work
```js
async run(req, res) {
	if (req.headers.referer !== 'http://localhost:8081/upload')
	return res.sendStatus(403);
```

As you see here even the website has a token!
![image](https://user-images.githubusercontent.com/11579313/123133057-45939b00-d447-11eb-8c06-f158a5d84ace.png)

**Comment by Kadantte** [comment]
Closed for no response.
