### ISSUE TITLE
Bug filtering tags with hyphen

### ISSUE THREAD

**Issue by Pepijn98** [brussell98/catgirls-api#18]
Trying to filter out images with the `off-shoulder shirt` tag by using `-"off-shoulder shirt"` but it seems at https://github.com/Nekos-moe/api/blob/master/api/v1/routes/ImageSearchPOST.js#L69 all hyphens are being replaced and not just the first. This is the same for other tags with a hyphen in them and makes it impossible to filter out images with such tags.

**Comment by brussell98** [comment]
Fixed
